services:
  carmanagement:
    image: ${DOCKER_REGISTRY-}carmanagement
    build:
      context: .
      dockerfile: CarManagement/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mynetwork
    command: ["sh", "-c", "sleep 10 && dotnet CarManagement.dll"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "CarManagementAPIDb"
      POSTGRES_USER: "shamil"
      POSTGRES_PASSWORD: "shamil1998"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shamil -d CarManagementAPIDb"]
      interval: 5s
      timeout: 5s
      retries: 10
    

volumes:
  pg_data:

networks:
  mynetwork: